# Generated by Django 3.1.3 on 2020-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name="Прізвище та ім'я")),
                ('description', models.CharField(max_length=300, verbose_name='Короткий текст')),
                ('fb', models.CharField(max_length=150, verbose_name='Фб-профіль посилання')),
                ('linkedin', models.CharField(max_length=150, verbose_name='Linkedin-профіль посилання')),
                ('alt', models.CharField(max_length=300, verbose_name='Alt текст')),
                ('image', models.ImageField(upload_to='speakers_pictures', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Спікер',
                'verbose_name_plural': 'Спікери',
            },
        ),
    ]
