# Generated by Django 3.1.3 on 2020-11-09 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='news_pictures', verbose_name='Зображення')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('alt', models.CharField(max_length=300, verbose_name='Alt текст')),
            ],
            options={
                'verbose_name_plural': 'Новини',
            },
        ),
    ]
