# Generated by Django 3.1.3 on 2020-11-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
