# Generated by Django 3.1.3 on 2020-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_hidden',
            field=models.BooleanField(null=True, verbose_name='Показувати поле'),
        ),
    ]
