# Generated by Django 3.1.3 on 2020-11-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201111_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(verbose_name='Сховати секцію')),
            ],
        ),
    ]
