# Generated by Django 3.1.3 on 2020-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sectionoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionoff',
            options={'verbose_name': 'Секція', 'verbose_name_plural': 'Секції'},
        ),
        migrations.AddField(
            model_name='sectionoff',
            name='section_name',
            field=models.CharField(max_length=30, null=True, verbose_name="Ім'я секції"),
        ),
        migrations.AlterField(
            model_name='sectionoff',
            name='is_hidden',
            field=models.BooleanField(verbose_name='Сховати секцію?'),
        ),
    ]
