# Generated by Django 3.1.3 on 2020-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201112_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionoff',
            name='is_hidden',
            field=models.BooleanField(verbose_name='Показувати секцію?'),
        ),
    ]
