# Generated by Django 3.1.3 on 2020-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201112_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name="Ім'я користувача")),
                ('description', models.CharField(max_length=300, verbose_name='Відгук')),
            ],
        ),
    ]
