# Generated by Django 3.1.3 on 2020-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_singup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефону'),
        ),
    ]
