# Generated by Django 3.1.3 on 2020-12-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201211_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=100, verbose_name="Ім'я користувача"),
        ),
        migrations.AlterField(
            model_name='singup',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='singup',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='singup',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Короткий текст'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Прізвище та ім'я"),
        ),
    ]
