# Generated by Django 3.1.3 on 2020-11-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_hidden',
            field=models.BooleanField(null=True, verbose_name='Сховати поле'),
        ),
    ]
